import Foundation

// MARK: - Legal Disclaimer

/// All legal strings in one place. Shown in UI and embedded in PDF exports.
public enum Legal {

    /// Primary disclaimer — must be visible on every result screen.
    public static let disclaimer = """
        This app provides mathematical simulations for educational purposes only \
        and does not constitute financial advice. All calculations are based on \
        standard reducing-balance EMI formulas. Actual loan terms may vary by lender. \
        Please consult a qualified financial advisor before making loan decisions.
        """

    /// Short version for compact UI areas (e.g., below charts).
    public static let shortDisclaimer = """
        For educational purposes only. Not financial advice.
        """

    /// PDF export footer.
    public static let pdfFooter = """
        Generated by Smart EMI Optimizer. Mathematical simulation only — \
        not financial advice. Verify with your lender before acting.
        """
}
